### Linear Regression Training

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
## Loading necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score

## Load the dataset
df = pd.read_csv('/content/drive/MyDrive/ImpactSense_Oct25/data/earthquakes_data_preprocessed.csv')

In [5]:
df.head()

,depth,rms,Mw,damage_potential,urbanity_indicator,risk_score,decade
0,-0.430568,0.340968,1.475494,1.340698,1,4.928040,0.0
1,-0.430568,0.303303,1.199571,1.212156,1,4.678560,0.0
2,-0.291258,0.480096,2.517872,1.261983,0,0.256667,0.0
3,-0.430568,0.441408,2.211290,1.683476,0,0.500000,0.0
4,-0.430568,0.355616,1.582798,1.390686,1,5.026810,0.0

In [6]:
# Split the data into features and targets
X = df.drop(columns=['risk_score'])
y = df['risk_score']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.head()

,depth,rms,Mw,damage_potential,urbanity_indicator,decade
47826,-0.263396,1.049168,0.960437,0.451813,1,0.750000
34205,-0.263396,1.471558,-0.854527,-0.393648,0,0.666667
9084,-0.430568,0.094053,-0.333338,0.498038,0,0.416667
99715,-0.477005,-1.231740,-1.467690,0.249462,1,1.000000
82570,-0.504867,-0.978306,-0.854527,0.745858,1,0.916667

In [7]:
## Build and train the Linear Regression Model
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [8]:
## Model Evaluation
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R-Squared: {r2}")

Mean Squared Error: 16.911596967638022
R-Squared: 0.20436315103293812

## Task:
- Train this model by implementing `hyperparameter tuning` and `cross-validation` techniques and write a report on it.

In [9]:
## Hyperparameter Tuning with GridSearchCV
from sklearn.model_selection import GridSearchCV

# Initialize model
model = LinearRegression()

# Define hyperparameter space to tune
param_grid = {
    'fit_intercept': [True, False],
    'copy_X': [True, False],
    'positive':[True, False],
    'n_jobs':[1, None]
}

# Initialize GridSearchCV with 5-fold cross-validation
grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=5)

# Fit to training data
grid_search.fit(X_train, y_train)

# Best parameters and best score
print("Best Hyperparameters: ", grid_search.best_params_)
print("Best CV Score: ", grid_search.best_score_)

Best Hyperparameters:  {'copy_X': True, 'fit_intercept': True, 'n_jobs': 1, 'positive': False}
Best CV Score:  0.2035033481919813

In [10]:
## Cross-validation to assess model performance
from sklearn.model_selection import cross_val_score
import numpy as np

model = LinearRegression()

# Perform 5-fold cross-validation
scores = cross_val_score(model, X_train, y_train, cv=5, scoring='neg_mean_squared_error')

print(f"R2 Scores for each fold: {scores}")
print(f"Average R2 Score: {np.mean(scores)}")

R2 Scores for each fold: [-18.96514895 -15.11637123 -19.90541423 -14.65657686 -15.41133081]
Average R2 Score: -16.810968416713443

# Understanding/Observation

**Dataset Split**


*   took the dataset and split it into training and testing parts 20% for testing.

**Linear Regression**
  

*   trained a plain, default Linear Regression model on the training set and tested it with mean square error and R2.
*   Mean Squared Error (MSE) for how far off the predictions are

*   R² score for how well the model explains the varianceR² score for how well the model explains the variance

**Hyperparameter Tuning**
used to see whether tweaking the model’s settings could make it better.
GridSearchCV tried permutation in
*   fit_intercept
*   copy_X
*   positive
*   n_jobs

tried every possible mix, ran cross-validation on each and showed the best score and parameter

**Cross-Validation**
used for testing

*   Split data into 5 equal parts
*   Train on 4 parts
*   Test on the leftover 1
*   Rotate this until each part has been the test set once